"""add_xyz_column

Revision ID: 36553ddb7f78
Revises: 002
Create Date: 2026-01-31 14:47:58.704714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36553ddb7f78'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default so existing rows get a value (avoids NOT NULL violation)
    op.add_column('countries', sa.Column('phone_code', sa.String(length=16), nullable=False, server_default=''))
    op.add_column('countries', sa.Column('display_order', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.alter_column('countries', 'region',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_constraint('countries_code_key', 'countries', type_='unique')
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index('ix_countries_region', 'countries', ['region'], unique=False)
    op.create_table_comment(
        'countries',
        'Countries with optional region for filtering',
        existing_comment=None,
        schema=None
    )
    op.add_column('states', sa.Column('display_order', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.create_table_comment(
        'states',
        'States/provinces per country',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_onboarding', 'country_phone_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_onboarding', 'country_phone_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_table_comment(
        'states',
        existing_comment='States/provinces per country',
        schema=None
    )
    op.drop_column('states', 'display_order')
    op.drop_table_comment(
        'countries',
        existing_comment='Countries with optional region for filtering',
        schema=None
    )
    op.drop_index('ix_countries_region', table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.create_unique_constraint('countries_code_key', 'countries', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('countries', 'region',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('countries', 'display_order')
    op.drop_column('countries', 'phone_code')
    # ### end Alembic commands ###
